#version 460 core
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_ray_query : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_buffer_reference : enable
#extension GL_EXT_scalar_block_layout : enable

//
layout( push_constant ) uniform constants
{
	uint64_t bufferAddress;
} PC;

//
layout (set = 0, binding = 0) uniform texture2D textures[];
layout (set = 0, binding = 1, rgba8) uniform image2D images[];
layout (set = 1, binding = 0) uniform sampler samplers[];

//
layout (set = 2, binding = 0, scalar) uniform MData { uint offset; };

//
layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

//
layout (buffer_reference, std430, buffer_reference_align = 16) buffer blockType { uint value; };

//
void main() {
	blockType(PC.bufferAddress + gl_GlobalInvocationID.x*4).value = offset + gl_GlobalInvocationID.x;
}
